const thinkingPhrases = [
  'Counting totems...',
  'Totems are conferring...',
  'Spilling the totems...',
  'Totem there, thinking that...',
  'Claude and totems, scheming...',
  'Brewing a fresh pot of ideas...',
  'Totem whispering...',
  'Sorting totems by vibe...',
  'Claude is totem-storming...',
  'Consulting the magic totems...',
  'Rolling totems across the table...',
  'Planting thought-totems...',
  'Claude is hugging a totem...',
  'Sharing secrets with totems...',
  'High-fiving a totem...',
  'Totems are doing a little dance...',
  'Claude and totems, on an adventure...',
  'Asking the totems nicely...',
  'Warming up the totem engine...',
  'Totem buddies at work...',
  'Flicking through the totem journal...',
  'Claude is teaching totems to sing...',
  'Having a totem picnic...',
  'Polishing the finest totems...',
  'Totem orchestra tuning up...',
  'Claude is juggling totems...',
  'Tiptoeing through the totem garden...',
  'Playing hide and seek with totems...',
  'Totem council in session...',
  'Claude is knitting a totem sweater...',
  'Totems are stretching their legs...',
  'Sending carrier totems...',
  'Claude is painting totems...',
  'Totem think tank activated...',
  'Stacking totems carefully...',
  'Claude is reading totems a story...',
  'Totems are whispering back...',
  'Building a totem fort...',
  'Claude and totems, stargazing...',
  'Shuffling the totem deck...',
  'Tossing totems into the idea jar...',
  'Claude is giving totems a pep talk...',
  'Balancing totems on a spoon...',
  'Totems are putting on tiny hats...',
  'Claude is drawing a totem map...',
  'Totem parade in progress...',
  'Comparing notes with totems...',
  'Claude is doing totem yoga...',
  'Totems are writing poetry...',
  'Assembling the totem squad...',
];

export function pickThinkingPhrase(): string {
  return thinkingPhrases[Math.floor(Math.random() * thinkingPhrases.length)];
}
