const thinkingPhrases = [
  'Counting beans...',
  'Beans are conferring...',
  'Spilling the beans...',
  'Bean there, thinking that...',
  'Claude and beans, scheming...',
  'Brewing a fresh pot of ideas...',
  'Bean whispering...',
  'Sorting beans by vibe...',
  'Claude is bean-storming...',
  'Consulting the magic beans...',
  'Rolling beans across the table...',
  'Planting thought-beans...',
  'Claude is hugging a bean...',
  'Sharing secrets with beans...',
  'High-fiving a bean...',
  'Beans are doing a little dance...',
  'Claude and beans, on an adventure...',
  'Asking the beans nicely...',
  'Warming up the bean engine...',
  'Bean buddies at work...',
  'Flicking through the bean journal...',
  'Claude is teaching beans to sing...',
  'Having a bean picnic...',
  'Polishing the finest beans...',
  'Bean orchestra tuning up...',
  'Claude is juggling beans...',
  'Tiptoeing through the bean garden...',
  'Playing hide and seek with beans...',
  'Bean council in session...',
  'Claude is knitting a bean sweater...',
  'Beans are stretching their legs...',
  'Sending carrier beans...',
  'Claude is painting beans...',
  'Bean think tank activated...',
  'Stacking beans carefully...',
  'Claude is reading beans a story...',
  'Beans are whispering back...',
  'Building a bean fort...',
  'Claude and beans, stargazing...',
  'Shuffling the bean deck...',
  'Tossing beans into the idea jar...',
  'Claude is giving beans a pep talk...',
  'Balancing beans on a spoon...',
  'Beans are putting on tiny hats...',
  'Claude is drawing a bean map...',
  'Bean parade in progress...',
  'Comparing notes with beans...',
  'Claude is doing bean yoga...',
  'Beans are writing poetry...',
  'Assembling the bean squad...',
];

export function pickThinkingPhrase(): string {
  return thinkingPhrases[Math.floor(Math.random() * thinkingPhrases.length)];
}
